// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
extern int tcpclient(const char * text);

void borrow_button_pressed(lv_event_t * e)
{
	// Your code here
	tcpclient("1");
}

void return_button_pressed(lv_event_t * e)
{
	// Your code here
	tcpclient("1");
}
