// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BORROW = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_BORROW, 200);
    lv_obj_set_height(ui_BORROW, 100);
    lv_obj_set_x(ui_BORROW, 636);
    lv_obj_set_y(ui_BORROW, 127);
    lv_obj_set_align(ui_BORROW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BORROW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BORROW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BORROW, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BORROW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURN = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_RETURN, 200);
    lv_obj_set_height(ui_RETURN, 100);
    lv_obj_set_x(ui_RETURN, 650);
    lv_obj_set_y(ui_RETURN, 302);
    lv_obj_set_align(ui_RETURN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RETURN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RETURN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TextArea1 = lv_textarea_create(ui_Screen1);
    lv_obj_set_width(ui_TextArea1, 900);
    lv_obj_set_height(ui_TextArea1, 300);
    lv_obj_set_x(ui_TextArea1, 510);
    lv_obj_set_y(ui_TextArea1, 600);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "\nPRESS IT!");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_letter_space(ui_TextArea1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_TextArea1, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextArea1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_36, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextArea1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextArea1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextArea1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextArea1, 20, LV_PART_MAIN | LV_STATE_DEFAULT);



    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_emoj1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, 0);
    lv_obj_set_y(ui_Image1, -200);
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_BORROW, ui_event_BORROW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RETURN, ui_event_RETURN, LV_EVENT_ALL, NULL);

}
