// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BORROW = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_BORROW, lv_pct(10));
    lv_obj_set_height(ui_BORROW, lv_pct(10));
    lv_obj_set_x(ui_BORROW, lv_pct(40));
    lv_obj_set_y(ui_BORROW, lv_pct(10));
    lv_obj_set_align(ui_BORROW, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BORROW, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BORROW, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BORROW, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_BORROW, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RETURN = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_RETURN, lv_pct(10));
    lv_obj_set_height(ui_RETURN, lv_pct(10));
    lv_obj_set_x(ui_RETURN, lv_pct(40));
    lv_obj_set_y(ui_RETURN, lv_pct(30));
    lv_obj_set_align(ui_RETURN, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RETURN, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_RETURN, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image1 = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_Image1, &ui_img_emoj1_png);
    lv_obj_set_width(ui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image1, lv_pct(0));
    lv_obj_set_y(ui_Image1, lv_pct(-25));
    lv_obj_set_align(ui_Image1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_wordshow = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_wordshow, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_wordshow, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_wordshow, 0);
    lv_obj_set_y(ui_wordshow, 137);
    lv_obj_set_align(ui_wordshow, LV_ALIGN_CENTER);
    lv_label_set_text(ui_wordshow, "Press It!\n\n");
    lv_obj_set_style_text_decor(ui_wordshow, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_wordshow, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_BORROW, ui_event_BORROW, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_RETURN, ui_event_RETURN, LV_EVENT_ALL, NULL);

}
